# Generated by Django 2.2.3 on 2019-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('servers', models.CharField(max_length=15)),
            ],
        ),
    ]
